---

ansible_user: sysadm

username: "sysadm"
groupname: "sysadm"

timezone: America/New_York

docker_network: "homelab"

docker_dir: /opt/homelab/docker_apps
data_dir: /opt/homelab/data

puid: "1000"
pgid: "1000"
