---
- import_playbook: admin_servers.yml
- import_playbook: ai_servers.yml
- import_playbook: devops_servers.yml
- import_playbook: ha_servers.yml
- import_playbook: id_servers.yml
- import_playbook: media_servers.yml
- import_playbook: minidev_servers.yml
- import_playbook: network_servers.yml
