---
- name: Setup the admin servers
  hosts: admin_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - homarr
    - wikijs
    - vaultwarden
    - nextcloud

- name: Setup the devops servers
  hosts: devops_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - nexus
    - plantuml

- name: Setup the home automation servers
  hosts: ha_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - esphome
    - mqtt
    - zigbee2mqtt

- name: Setup the media servers
  hosts: media_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - jellyfin

- name: Setup the network servers
  hosts: network_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - guacamole

- name: Setup the identification servers
  hosts: id_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - portainer
    - traefik
    - traefik_apps
    - keycloak

- name: Setup the mini development servers
  hosts: minidev_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - plantuml
    - traefik
    - traefik_apps
