---
- name: Setup the admin servers
  hosts: admin_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - homarr
    - wikijs
    - nextcloud

- name: Setup the devops servers
  hosts: devops_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower

- name: Setup the home automation servers
  hosts: ha_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - homeassistant

- name: Setup the network servers
  hosts: network_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - guacamole
