---
- name: Setup the admin servers
  hosts: admin_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - homarr
    - wikijs
    - vaultwarden

- name: Setup the devops servers
  hosts: devops_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - nexus

- name: Setup the home automation servers
  hosts: ha_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - homeassistant
    - nodered
    - mqtt

- name: Setup the media servers
  hosts: media_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - jellyfin

- name: Setup the network servers
  hosts: network_servers
  become: true
  roles:
    - common
    - docker
    - portainer
    - traefik
    - watchtower
    - guacamole
    - unifictrl
