---
- name: Validate watchtower configuration
  ansible.builtin.include_tasks: validate.yml
  when: watchtower_enabled | bool

- name: Install and configure watchtower
  ansible.builtin.include_tasks: install.yml
  when: watchtower_enabled | bool

- name: Verify watchtower
  ansible.builtin.include_tasks: verify.yml
  when:
    - watchtower_enabled | bool
    - watchtower_verify_enabled | bool
