services:
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    restart: unless-stopped
    ports:
      - "6052:6052"    
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true      
    volumes:
      - {{ esphome_config_dir }}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - esphome      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esphome.entrypoints=http"
      - "traefik.http.routers.esphome.rule=Host(`esphome.{{ domain }}`)"
      - "traefik.http.middlewares.esphome-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.esphome.middlewares=esphome-https-redirect"
      - "traefik.http.routers.esphome-secure.entrypoints=https"
      - "traefik.http.routers.esphome-secure.rule=Host(`esphome.{{ domain }}`)"
      - "traefik.http.routers.esphome-secure.tls=true"
      - "traefik.http.routers.esphome-secure.service=esphome"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052"
      - "traefik.docker.network={{ docker_network }}"

networks:
  esphome:
    name: "{{ docker_network }}"
    external: true
