FROM ruby:3.3-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    git \
    openssh-client \
    ca-certificates \
    && mkdir -p /root/.ssh \
    && chmod 700 /root/.ssh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /srv/jekyll

EXPOSE 4000