---
wikijs_enabled: true

wikijs_stack_name: wikijs
wikijs_container_name: wikijs

wikijs_app_dir: "{{ docker_dir }}/wikijs"
wikijs_data_dir: "{{ data_dir }}/wikijs"
wikijs_ssh_dir: "{{ wikijs_app_dir }}/ssh"
wikijs_ssh_key_filename: wikijs_rsa

# Supported values: postgres, sqlite3
wikijs_database: postgres

# Runtime
wikijs_image: ghcr.io/requarks/wiki:2
wikijs_restart_policy: unless-stopped
wikijs_container_port: 3000

# Networking
wikijs_bind_ip: "{{ server_bind_ip }}"
wikijs_host_port: "{{ app_port_wikijs }}"
wikijs_docker_network: "{{ docker_network }}"

# Postgres
wikijs_postgres_image: postgres:15-alpine
wikijs_postgres_container_name: wikijs-postgres
wikijs_postgres_db: wiki
wikijs_postgres_user: wikijs
wikijs_postgres_password: W1k1jsR0cks

# SQLite
wikijs_sqlite_filepath: /wiki/data/db.sqlite

# Verification
wikijs_verify_enabled: true
wikijs_verify_timeout: 120
