services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 0.0.0.0:1883:1883
      - 0.0.0.0:9001:9001    
    environment:
      - mqtt_DASHBOARD_USE_PING=true      
    volumes:
      - "{{ mqtt_config_dir }}:/mosquitto/config"
      - "{{ mqtt_data_dir }}:/mosquitto/data"
      - "{{ mqtt_log_dir }}:/mosquitto/log"
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mqtt      
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1883"
      - "traefik.tcp.services.mqtt_websocket.loadbalancer.server.port=9001"
      - "traefik.tcp.routers.tcpr_mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.tcpr_mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tcpr_mqtt.service=mqtt"
      - "traefik.tcp.routers.tcpr_mqtt_websocket.entrypoints=websocket"
      - "traefik.tcp.routers.tcpr_mqtt_websocket.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.tcpr_mqtt_websocket.service=mqtt_websocket"
      - "traefik.docker.network={{ docker_network }}"

networks:
  mqtt:
    name: "{{ docker_network }}"
    external: true
