---
- name: Validate Nextcloud configuration
  ansible.builtin.include_tasks: validate.yml
  when: nextcloud_enabled | bool

- name: Install and configure Nextcloud
  ansible.builtin.include_tasks: install.yml
  when: nextcloud_enabled | bool

- name: Verify Nextcloud
  ansible.builtin.include_tasks: verify.yml
  when:
    - nextcloud_enabled | bool
    - nextcloud_verify_enabled | bool
