services:

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "10001:10001"
    volumes:
      - "{{ nexus_data_dir }}:/nexus-data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nexus      
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nexus.entrypoints=https"
      - "traefik.http.routers.nexus.rule=Host(`nexus.brulenet.dev`)"
      - "traefik.http.routers.nexus.tls=true"
      - "traefik.http.routers.nexus.service=nexus-service"
      - "traefik.http.services.nexus-service.loadbalancer.server.port=8081"

      - "traefik.http.routers.docker.entrypoints=https"
      - "traefik.http.routers.docker.rule=Host(`docker.brulenet.dev`)"
      - "traefik.http.routers.docker.tls=true"
      - "traefik.http.routers.docker.service=docker-service"
      - "traefik.http.services.docker-service.loadbalancer.server.port=10001"
      
      - "traefik.docker.network=homelab"


networks:
  nexus:
    name: "{{ docker_network }}"
    external: true
