services:

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "10001:10001"
    volumes:
      - "{{ nexus_data_dir }}:/nexus-data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nexus      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.entrypoints=http"
      - "traefik.http.routers.nexus.rule=Host(`nexus.{{ domain }}`)"
      - "traefik.http.middlewares.nexus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nexus.middlewares=nexus-https-redirect"
      - "traefik.http.routers.nexus-secure.entrypoints=https"
      - "traefik.http.routers.nexus-secure.rule=Host(`nexus.{{ domain }}`)"
      - "traefik.http.routers.nexus-secure.tls=true"
      - "traefik.http.routers.nexus-secure.service=nexus"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"

      - "traefik.http.routers.docker-registry.rule=Host(`docker.{{ domain }}`)"
      - "traefik.http.routers.docker-registry.tls=true"
      - "traefik.http.routers.docker-registry.service=docker-service"
      - "traefik.http.services.docker-service.loadbalancer.server.port=10001"
      
      - "traefik.docker.network={{ docker_network }}"

networks:
  nexus:
    name: "{{ docker_network }}"
    external: true
