---
- name: Validate Nexus configuration
  ansible.builtin.include_tasks: validate.yml
  when: nexus_enabled | bool

- name: Install and configure Nexus
  ansible.builtin.include_tasks: install.yml
  when: nexus_enabled | bool

- name: Verify Nexus
  ansible.builtin.include_tasks: verify.yml
  when:
    - nexus_enabled | bool
    - nexus_verify_enabled | bool
