---
- name: Validate Gitea configuration
  ansible.builtin.include_tasks: validate.yml
  when: gitea_enabled | bool

- name: Install and configure Gitea
  ansible.builtin.include_tasks: install.yml
  when: gitea_enabled | bool

- name: Verify Gitea
  ansible.builtin.include_tasks: verify.yml
  when:
    - gitea_enabled | bool
    - gitea_verify_enabled | bool
