---
- name: Validate Wiki.js configuration
  ansible.builtin.include_tasks: validate.yml
  when: wikijs_enabled | bool

- name: Install and configure Wiki.js
  ansible.builtin.include_tasks: install.yml
  when: wikijs_enabled | bool

- name: Verify Wiki.js
  ansible.builtin.include_tasks: verify.yml
  when:
    - wikijs_enabled | bool
    - wikijs_verify_enabled | bool
