---
- name: Validate Vaultwarden configuration
  ansible.builtin.include_tasks: validate.yml
  when: vaultwarden_enabled | bool

- name: Install and configure Vaultwarden
  ansible.builtin.include_tasks: install.yml
  when: vaultwarden_enabled | bool

- name: Verify Vaultwarden
  ansible.builtin.include_tasks: verify.yml
  when:
    - vaultwarden_enabled | bool
    - vaultwarden_verify_enabled | bool
