---
# tasks file for nodered

- name: Create nodered base directory
  ansible.builtin.file:
    path: "{{ nodered_dir }}"
    state: directory
    mode: '0755'
    owner: sysadm
    group: sysadm
    access_time: preserve
    modification_time: preserve

- name: copy nodered files
  template:
    src: templates/{{ item }}
    dest: "{{ nodered_dir }}"
  loop:
    - docker-compose.yml

- name: Create nodered data directory
  ansible.builtin.file:
    path: "{{ nodered_data_dir }}"
    state: directory
    mode: '0755'
    owner: sysadm
    group: sysadm
    access_time: preserve
    modification_time: preserve

- name: Run nodered docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ nodered_dir }}"
    files:
      - docker-compose.yml
