---
- name: Validate Node-RED configuration
  ansible.builtin.include_tasks: validate.yml
  when: nodered_enabled | bool

- name: Install and configure Node-RED
  ansible.builtin.include_tasks: install.yml
  when: nodered_enabled | bool

- name: Verify Node-RED
  ansible.builtin.include_tasks: verify.yml
  when:
    - nodered_enabled | bool
    - nodered_verify_enabled | bool
