---
- name: Wait for Node-RED HTTP endpoint
  ansible.builtin.uri:
    url: "http://{{ nodered_bind_ip }}:{{ nodered_host_port }}"
    method: GET
    status_code:
      - 200
      - 302
      - 401
    validate_certs: false
  register: nodered_verify_result
  retries: "{{ (nodered_verify_timeout | int / 5) | round(0, 'ceil') | int }}"
  delay: 5
  until: nodered_verify_result.status in [200, 302, 401]
