services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    environment:
      - PUID={{ puid }}
      - PGID={{ pgid }}
      - JELLYFIN_PublishedServerUrl=https://jellyfin.brulenet.dev
    volumes:
      - "{{ jellyfin_config_dir }}:/config"
      - "{{ jellyfin_cache_dir }}:/cache"
      - /etc/localtime:/etc/localtime:ro
    networks:
      - jellyfin      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.{{ domain }}`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.{{ domain }}`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network={{ docker_network }}"

networks:
  jellyfin:
    name: "{{ docker_network }}"
    external: true
