---
# tasks file for homeassistant

- name: Create homeassistant base directory
  ansible.builtin.file:
    path: "{{ homeassistant_dir }}"
    state: directory
    mode: '0755'
    owner: sysadm
    group: sysadm
    access_time: preserve
    modification_time: preserve

- name: copy homeassistant files
  template:
    src: templates/{{ item }}
    dest: "{{ homeassistant_dir }}"
  loop:
    - docker-compose.yml

- name: Create homeassistant config directory
  ansible.builtin.file:
    path: "{{ homeassistant_config_dir }}"
    state: directory
    mode: '0755'
    owner: sysadm
    group: sysadm
    access_time: preserve
    modification_time: preserve

- name: Run homeassistant docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ homeassistant_dir }}"
    files:
      - docker-compose.yml
