---
- name: Validate Home Assistant configuration
  ansible.builtin.include_tasks: validate.yml
  when: homeassistant_enabled | bool

- name: Install and configure Home Assistant
  ansible.builtin.include_tasks: install.yml
  when: homeassistant_enabled | bool

- name: Verify Home Assistant
  ansible.builtin.include_tasks: verify.yml
  when:
    - homeassistant_enabled | bool
    - homeassistant_verify_enabled | bool
