---
- name: Validate Home Assistant configuration
  ansible.builtin.include_tasks: validate.yml
  when: homeassistant_enabled | bool

- name: Install and configure Home Assistant
  ansible.builtin.include_tasks: install.yml
  when: homeassistant_enabled | bool

- name: Configure Home Assistant frontend
  ansible.builtin.include_tasks: frontend.yml
  when: homeassistant_enabled | bool

- name: Verify Home Assistant
  ansible.builtin.include_tasks: verify.yml
  when:
    - homeassistant_enabled | bool
    - homeassistant_verify_enabled | bool

- name: Configure Home Assistant Ping hosts
  ansible.builtin.include_tasks: ping_hosts.yml
  when:
    - homeassistant_enabled | bool
    - homeassistant_api_token | length > 0
    - homeassistant_ping_hosts | length > 0
