---
- name: Setup the iot automation servers
  hosts: iot_servers
  become: true
  roles:
    - common
    - docker
    - watchtower
    - traefik
    - traefik_apps
    - esphome
    - homeassistant
    - mqtt
    - nodered
    - zigbee2mqtt
